### ISSUE TITLE
Confusing error if asset name contains a space

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-asset-manager#52]
If an asset name contains a space (e.g., `Map Layers`) then a confusing error is displayed ("Unexpected '<' at: line 1 column 1 (char 0)"), but the asset is apparently still created.

<img width="908" alt="space-error" src="https://user-images.githubusercontent.com/338833/56148695-b9ea6e00-5fa2-11e9-8d35-4a35860c9d4b.png">

**Comment by senakafdo** [comment]
Also, the word `Description` seen in this image is rendered in two lines. We can set a minimum width for the divisions to avoid this happening or down-scale the font-size with CSS. Bootstrap should also provide automatic resizing OOTB if the proper class names were set.

**Comment by jamesscottbrown** [comment]
Yes: this window is half the width of my macbook pro, and at this size there are several layout issues (one was fixed as https://github.com/ove/ove-asset-manager/issues/17). I also find that the width threshold at which the transition from the full header to the collapsed 'hamburger menu' happens is too high.

**Comment by oserban** [comment]
@senakafdo first of all the proper classes were used. I had to fine tune everything because Bootstrap is reacting a bit strange on non-bootstrap components (e.g. the tags dropdown). I tweaked a bit more the UI.

On the actions menu overlapping I previously used a grid to display the components. I switched to a dynamic grid position which seems to fix the problem for low resolutions.

**Comment by oserban** [comment]
The UI tweaks were made as part of #50 

I also tweaked the navbar slightly (removed the branding + collapsing should happen on md size screens only)
